### ISSUE TITLE
the edns maybe not success

### ISSUE THREAD

**Issue by finxeng** [vislee/lua-resty-dns-server#16]
`fengxin@fengxins-MacBook-Air ~ % dig -v
DiG 9.9.3`

start the lua-resty-dns-server on localhost

`fengxin@fengxins-MacBook-Air ~ % dig @localhost www.fengxin.com +client=159.138.88.145

; <<>> DiG 9.9.3 <<>> @localhost www.fengxin.com +client=159.138.88.145
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52034
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.fengxin.com.		IN	A

;; AUTHORITY SECTION:
www.fengxin.com.	600	IN	NS	8.8.8.8.

;; Query time: 6 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Jul 14 18:24:27 CST 2020
;; MSG SIZE  rcvd: 69

fengxin@fengxins-MacBook-Air ~ % `

then this is ok!
and then  lost  +client paramter

`fengxin@fengxins-MacBook-Air ~ % dig @localhost www.fengxin.com

; <<>> DiG 9.9.3 <<>> @localhost www.fengxin.com
; (2 servers found)
;; global options: +cmd
;; connection timed out; no servers could be reached
fengxin@fengxins-MacBook-Air ~ % 
`
then error log

`2020/07/14 18:27:50 [error] 11074#1563068: *6 lua entry thread aborted: runtime error: ./commons/dns/server.lua:286: bad argument #1 to 'lshift' (number expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'lshift'
	./commons/dns/server.lua:286: in function 'decode_request'
	.../shareit-mcp-dns/model/service/resolution_dns_53_udp.lua:22: in main chunk, udp client: 127.0.0.1, server: 0.0.0.0:53`

see the code with server.lua:286

`local opt_code_hi, opt_code_lo = byte(self.buf, self.pos - 1, self.pos)
            local opt_code = lshift(opt_code_hi, 8) + opt_code_lo`

the question ,I am lost the +client paramter when use dig, maybe  maybu the dig think the edns paramter is null,so the server code 286 line opt_code_hi and opt_code_lo all is null?

do i need check the opt_code_hi and opt_code_lo is or not null in the server.lua

**Comment by selboo** [comment]
@selboo
