### ISSUE TITLE
ipv6 简写地址 多了一个 "0"

### ISSUE THREAD

**Issue by selboo** [vislee/lua-resty-dns-server#2]
ipv6 地址简写 多了一个 "0"

完整地址: 2400:89c0:1022:0657:0000:0000:0152:0150 返回正常

`dns:create_aaaa_answer("a.test.com", 100, "2400:89c0:1022:0657:0000:0000:0152:0150")`

`dig @127.0.0.1 a.test.com -p 2953 AAAA`
`a.test.com.		100	IN	AAAA	2400:89c0:1022:657::152:150`

简写地址: 2400:89c0:1022:657::152:150 

`dns:create_aaaa_answer("a.test.com", 100, "2400:89c0:1022:657::152:150")`

`dig @127.0.0.1 a.test.com -p 2953 AAAA`
`a.test.com.		100	IN	AAAA	2400:89c0:1022:657::152:150:0`

后面多了一个 "0"

@vislee

**Comment by vislee** [comment]
目前的版本没有支持简写IPV6地址，你可以修复一下这个函数`_encode_aaaa`提个PR。
